# Generated by Django 2.1.5 on 2019-02-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('orden', models.SlugField(unique=True)),
            ],
        ),
    ]
