# Generated by Django 2.1.5 on 2019-02-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academiya', '0003_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='id',
        ),
        migrations.AddField(
            model_name='answers',
            name='candidate',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academiya.Candidate'),
            preserve_default=False,
        ),
    ]
