# Generated by Django 2.1.5 on 2019-03-01 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academiya', '0004_auto_20190227_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academiya.Test_task')),
                ('planet', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='academiya.Planet')),
            ],
        ),
    ]
